apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: exam
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # initContainers:
      #   - name: wait-for-backend
      #     image: darthcabs/tiny-tools:1
      #     args:
      #       - /bin/bash
      #       - -c
      #       - >
      #         set -x;
      #         while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://backend:5000)" != "200" ]]; do
      #           echo '.'
      #           sleep 15;
      #         done
      containers:
        - name: frontend
          image: guizo792/containerization-exam-frontend:v1.1
          ports:
            - containerPort: 80
