apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: exam
spec:
  selector:
    app: mongodb-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32000
