apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: exam
  labels:
    app: mongodb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-service
          image: mongo
          imagePullPolicy: IfNotPresent
          ports:
            - name: mongodb-port
              containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/mongo
          # livenessProbe:
          #   tcpSocket:
          #     port: mongodb-port
          #   timeoutSeconds: 15
          #   periodSeconds: 120

          # readinessProbe:
          #   httpGet:
          #     port: mongodb-port
          #     path: /healthCheck
          #   timeoutSeconds: 15
          #   periodSeconds: 13

          # startupProbe:
          #   tcpSocket:
          #     port: mongodb-port
          #   failureThreshold: 10
          #   periodSeconds: 10
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
