apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: exam
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: guizo792/containerization-exam-backend:v1.1
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mongo-root-username
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mongo-root-password
